### ISSUE TITLE
Fix broken help go URL

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#1604]
Once we're confident it's safe to do so, we should fix the "broken" go URL here: https://github.com/adobe-photoshop/spaces-design/blob/ada2ebaeb76b1465308bbfcd96fc136ea4920598/src/js/jsx/help/FirstLaunch.jsx#L78

It should not have a ".html" suffix.

**Comment by chadrolfs** [comment]
This is fixed now, isn't it?

**Comment by iwehrman** [comment]
Not quite fixed. The FirstLaunch component no longer links directly to help, but the menu item (in menu-actions) does, and still has the wrong URL. We should still fix that.

**Comment by iwehrman** [comment]
I pushed 8b31127da31445a3be6d9da787d87b01ba796790 to master to address this.
