### ISSUE TITLE
modal dialog alert: Could not use pen tool because of a program error.

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1681]
New doc, select Rect tool and drag out a shape within AB, select the Pen tool and click once to set an anchor point, click on the Rectangle 1 shape in layers panel, (pen tool still selected) click on canvas.

Result: modal dialog alert: Could not use pen tool because of a program error.

on Win you may get this as well when you try to set focus the Rect in the layers panel: 
`Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined` [Edit - Barkin: This is unrelated and fixed]

**Comment by chadrolfs** [comment]
After you click OK to the modal error dialog, if you set focus back to Shape 1 and click again, it will connect the first anchor point to the one you just set, essentially letting you continue to draw out the shape you started with the pen tool.

**Comment by volfied** [comment]
Ah, this has nothing to do with artboards. Our swap algorithm does one thing for the first situation, and another thing for the second situationa fter they're swapped, due to size differences in the layers.

I'll look into it, but we never tried to make our swap algorithm symmetric.

**Comment by volfied** [comment]
`barkin/1681`, Not a fan of the transfer skip FIXME comment in there so leaving this Fix in Progress for now.

**Comment by volfied** [comment]
I've fixed this in my branch... However, I think a better solution would be to start new pen layers instead of complaining about lack of use, which would make this a core bug. I'm still leaving my PR open to remedy the situation, but we should look into not needing that fix.

**Comment by mcilroyc** [comment]
I think @volfied is saying that this is fix fa realz now.  @chadrolfs

**Comment by chadrolfs** [comment]
Following original steps in issue, I still get modal error dialog.

**Comment by volfied** [comment]
Will be fixed in pgdv.max.672 with CL 1044284. 

As a side effect, any time layer selection changes, we erase the current sub path index now, so to be able to continue an open path in the selected layer, you'll need to click one of it's open anchors to activate that sub path.

**Comment by chadrolfs** [comment]
Apparently the core fix broke things on the other side of the fence.  They are reverting so this bug will once again re-occur.  Thanks to @fosterbrereton for the heads up.  Here is the core issue:
http://moriarty.corp.adobe.com/bug?bug=4071562

**Comment by chadrolfs** [comment]
Yep, it's back and I don't think we have time to come up with a solution.  For discussion.  I'm recommending kick to M4.

**Comment by chadrolfs** [comment]
https://watsonexp.corp.adobe.com//#bug=4075258

**Comment by tiburbage** [comment]
The Watson entry relating to this issue has been closed. We can revisit as a JIRA if it warrants that.
