### ISSUE TITLE
Non-empty groups are not exportable

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2376]
Selecting a non-empty group in layers panel shows "No supported layers selected" message.

**Comment by mcilroyc** [comment]
Fixed by above-reference PR.  back to @ktaki 

To determine if a layer should be exportable, we now look at its *child* bounds.  For regular layers, this is equivalent, but for groups it takes in to account its children.

**Comment by ktaki** [comment]
This is not fixed. Selecting a group with a shape layer still shows "No supported layers selected" message.

**Comment by mcilroyc** [comment]
My apologies @ktaki .  I believe I've refined the fix further in PR 2420.  When creating groups, our model is slightly different than if a document with existing groups is loaded.

**Comment by ktaki** [comment]
Verified the fix.
