### ISSUE TITLE
Overflowing text in non-English languages

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2571]
DE:
![image](https://cloud.githubusercontent.com/assets/1075154/10028514/bfa7d6da-6121-11e5-9e6b-05306302701d.png)

FR:
![image](https://cloud.githubusercontent.com/assets/1075154/10028518/c56b566e-6121-11e5-8186-98c637ba71c4.png)

JA:
![image](https://cloud.githubusercontent.com/assets/1075154/10028522/ccb61cc4-6121-11e5-852a-9c8583ca62c9.png)

**Comment by iwehrman** [comment]
@DivyaPrabhakar: can you just try to expand the widths of the inputs _a little bit_ to accommodate the wider strings as shown in the pictures above? It might not be possible for JA. I don't want to make any major changes right now; just small tweaks.

**Comment by iwehrman** [comment]
[Watson 4058099](https://watsonexp.corp.adobe.com/#bug=4058099)

**Comment by DivyaPrabhakar** [comment]
FBNC @iwehrman

**Comment by iwehrman** [comment]
Fixed by #2871 and #2918.

**Comment by fzhu1978** [comment]
![jpn_20151016 m 262](https://cloud.githubusercontent.com/assets/11431959/10615627/c29b07a4-7715-11e5-8a93-13bc6dae27dc.png)
Still have issue on Japanese.

**Comment by DivyaPrabhakar** [comment]
@iwehrman I'll take this again

**Comment by DivyaPrabhakar** [comment]
@fzhu1978 This has be fixed but it is not closed. Passing it back to you so you can verify the fix.

**Comment by chadrolfs** [comment]
Been sitting in FBNC for a while, @ktaki can you verify and close?  Thanks.

**Comment by jsbache** [comment]
Not a core bug. I am removing the ps core tag

**Comment by ktaki** [comment]
Only issue I found is in Japanese Effect panel. With Stroke, Size label has wrapped.

![screen shot 2015-10-26 at 3 08 07 pm](https://cloud.githubusercontent.com/assets/2029597/10744310/39f8bc08-7bf6-11e5-9632-30c9d8fb1ba0.png)

This can be deferred to M4.

**Comment by ktaki** [comment]
Looks good!
