### ISSUE TITLE
Modal dialogs are not centered correctly

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2795]
![image](https://cloud.githubusercontent.com/assets/1075154/10285288/04991ad6-6b3d-11e5-85c0-00e46fdcfb84.png)

![image](https://cloud.githubusercontent.com/assets/1075154/10285291/08975490-6b3d-11e5-896a-7e4f03269c74.png)

**Comment by placegraphichere** [comment]
I'm partially fixing this issue. Only export and intro dialogs. 

Search is a little more difficult since it tries to sit in the middle of the canvas, which is less reliably possible. See #2899

**Comment by placegraphichere** [comment]
This is now getting fully fixed in #2899

**Comment by iwehrman** [comment]
This is not quite fixed. The centering logic does not yet take the toolbar and the icon bar into account. A better fix will probably require that JS provide the dialog center coordinate when positioning the dialog. Reopening.

**Comment by designedbyscience** [comment]
Over for verification

**Comment by iwehrman** [comment]
Yep!
